### ISSUE TITLE
code

### ISSUE THREAD

**Issue by luoyizhi516** [abdelazizashraf123/shrimp-disease-classifiaction-and-behavior-detection-#1]
hi, brother, nice to meet you, I'm working on shrimp behavior, can provide your code to email: 571082793@qq.com

**Comment by abdelazizashraf123** [comment]
Dear luoyizhi516,
Sorry, but the company we worked with has the copyright to the code and the
prototype,
But if you need any consultation for any animal behavior analysis, feel
free to contact me. at this email
***@***.***
B.R,
Abdelaziz

**Comment by abdelazizashraf123** [comment]
check you email
